name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: rustup target add wasm32-wasi
    - name: Run simple test
      run: |
        cargo build --target wasm32-wasi --release --bin blob
        cargo build --target wasm32-wasi --release --bin cosmos
        cargo build --target wasm32-wasi --release --bin eventgrid
        cargo build --target wasm32-wasi --release --bin iothub
